version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      # specify the version
      - image: circleci/golang:1.9
      - image: instrumentisto/dep

    working_directory: /go/src/github.com/anhnguyentb/cws-publish
    steps:
      - checkout
      - setup_remote_docker

      #### Run dep
      - run: docker run --rm -v ${pwd}:/go/src/my/pkg/name -w /go/src/my/pkg/name ensure

      ### Run test
      - run: go test -v ./...

      ### Build
      - run: go build -o /go/bin/profiles -v