version: 2
defaults:
  working_directory: /go/src/github.com/anhnguyentb/cws-publish
jobs:
  build:
    docker:
    - image: instrumentisto/dep
    #      - image: docker:17.05.0-ce-git
    #      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/anhnguyentb/cws-publish
    steps:
    - checkout
    #      - setup_remote_docker

    #### Run dep
    - run: dep ensure -v
  gobuild:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/anhnguyentb/cws-publish
    steps:
    ### Run test
    - run: go test -v ./...

    ### Build
    - run: go build -o /go/bin/cws-publish -v