version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3

    environment:
      DOCKER_REGISTRY: anhnguyentb90/cws-publish

    working_directory: /go/src/github.com/anhnguyentb/cws-publish

    steps:
    - checkout
    - setup_remote_docker

    #### Run dep
    - run: |
        # create a dummy container which will hold a volume with code
        docker create -v /go/src/github.com/anhnguyentb/cws-publish --name go-dep alpine:3.4 /bin/bash
        docker cp /go/src/github.com/anhnguyentb/cws-publish/. go-dep:/go/src/github.com/anhnguyentb/cws-publish
        # start an application container using this volume
        docker run --rm --workdir /go/src/github.com/anhnguyentb/cws-publish --volumes-from go-dep:z instrumentisto/dep ensure -v
        docker cp go-dep:/go/src/github.com/anhnguyentb/cws-publish/vendor /go/src/github.com/anhnguyentb/cws-publish

    ### Run test
    - run: go test -v ./...

    ### Build
    - run: go build -o /go/bin/cws-publish -v

    ### Publish to Docker hub
    - run: |
        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_REGISTRY:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_REGISTRY:$TAG
        fi