version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.9
    - image: instrumentisto/dep

    working_directory: /go/src/github.com/anhnguyentb/cws-publish
    steps:
      - checkout

      #### Run dep
      - run: docker run --rm -v ${pwd}:/go/src/github.com/anhnguyentb/cws-publish -w /go/src/github.com/anhnguyentb/cws-publish ensure

      ### Run test
      - run: go test -v ./...

      ### Build
      - run: go build -o /go/bin/profiles -v